### ISSUE TITLE
not working with vue2.0 beta 5 or 6

### ISSUE THREAD

**Issue by wprater** [vuejs-templates/systemjs#3]
I updated to the latest beta `jspm install vue=vue@2.0.0-beta.6` and get this error

```
Uncaught TypeError: _e is not a function
    at Proxy.render (http://localhost:3001/build.js:3948:40)
    at VueComponent.Vue._render (http://localhost:3001/build.js:1579:24)
    at VueComponent.eval (http://localhost:3001/build.js:1193:23)
    at Watcher.get (http://localhost:3001/build.js:560:31)
    at new Watcher (http://localhost:3001/build.js:556:49)
    at VueComponent.Vue._mount (http://localhost:3001/build.js:1192:21)
    at init (http://localhost:3001/build.js:1401:13)
    at createElm (http://localhost:3001/build.js:2594:11)
    at Vue.patch [as __patch__] (http://localhost:3001/build.js:2908:11)
    at Vue._update (http://localhost:3001/build.js:1209:21)
2016-08-03 09:22:33.769 http://localhost:3001/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by yyx990803** [comment]
FYI we are no longer maintaining this template due to minimal interest in SystemJS from Vue users.  It is now officially recommended to use Webpack unless you have very specific reasons to avoid it.
